all: memory1 memory2 memory3 memory4 memory5a memory5b memory6

memory1: memory1.c
	gcc -o memory1.o memory1.c
memory2: memory2.c
	gcc -o memory2.o memory2.c
memory3: memory3.c
	gcc -o memory3.o memory3.c
memory4: memory4.c
	gcc -o memory4.o memory4.c
memory5a: memory5a.c
	gcc -o memory5a.o memory5a.c
memory5b: memory5b.c
	gcc -o memory5b.o memory5b.c
memory6: memory6.c
	gcc -o memory6.o memory6.c

clean:
	rm -rf *.o
